openapi: 3.0.0
info:
  title: TodoMVC
  version: 1.0.0
servers:
  - url: https://gcp-serverless-{env}.slamdev.net
    variables:
      env:
        default: dev
        enum:
          - dev
          - prod
security:
  - bearerAuth: []
paths:
  /api/items-endpoint:
    get:
      operationId: getItems
      responses:
        '200':
          description: Items
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemsListResponse'
        default:
          $ref: '#/components/responses/Error'
  /api/items-endpoint/{id}:
    get:
      operationId: getItem
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemResponse'
        default:
          $ref: '#/components/responses/Error'
    put:
      operationId: saveItem
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SaveItemRequest'
      responses:
        '200':
          description: Item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemResponse'
        default:
          $ref: '#/components/responses/Error'
    delete:
      operationId: deleteItem
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Deleted
        default:
          $ref: '#/components/responses/Error'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    Error:
      description: Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
  schemas:
    ErrorResponse:
      type: object
      properties:
        requestId:
          type: string
          format: uuid
        message:
          type: string
      required:
        - requestId
        - message
    SaveItemRequest:
      type: object
      properties:
        name:
          type: string
        completed:
          type: boolean
      required:
        - name
        - completed
    ItemResponse:
      type: object
      properties:
        requestId:
          type: string
          format: uuid
        item:
          $ref: '#/components/schemas/Item'
      required:
        - requestId
        - item
    ItemsListResponse:
      type: object
      properties:
        requestId:
          type: string
          format: uuid
        items:
          type: array
          items:
            $ref: '#/components/schemas/Item'
      required:
        - requestId
        - items
    Item:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        completed:
          type: boolean
      required:
        - id
        - name
        - completed
